language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run the test
script:
  - coverage run --omit="*/site-packages/*" manage.py test
after_success:
  COVERALLS_REPO_TOKEN=$token  coveralls