language: python
python:
  - "3.3"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

services:
 -postgresql
 
 before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres

# command to run the test
script:
  - source .env
  -  nosetests  --with-coverage
  
after_success: coveralls